---
title: "rgl runner"
author: "Nick Spyrison"
date: "29/05/2020"
output: html_document
---
# BASICALLY  call rglwidget() afterwards

```{r setup, include=FALSE}
options(rgl.useNULL=TRUE)
knitr::knit_hooks$set(webgl = hook_webgl)
knitr::opts_chunk$set(echo = TRUE)
library(rgl)


ns_knit_rgl <- function(expr, echoCode = FALSE, ){
  if(!(class(expr) %in% "call")) try(expr <- substitute(expr))
  if(!(class(expr) %in% "call")) 
    stop("Class of expr must be call. Try wrapping substitute around it.")
  knitr::knit_hooks$set(webgl = hook_webgl)
  knitr::opts_chunk$set(echo = echoCode)
  options(rgl.useNULL=TRUE)
  require("rgl")
  try(rgl.close())
  eval(expr)
  rglwidget()
}
```

```{r echo=FALSE, webgl=TRUE}
open3d()
plot3d( cube3d(col = "green") )
M <- par3d("userMatrix")
if (!rgl.useNULL())
  play3d( par3dinterp(time = (0:2)*0.75, userMatrix = list(M,
                                     rotate3d(M, pi/2, 1, 0, 0),
                                     rotate3d(M, pi/2, 0, 1, 0) ) ), 
        duration = 3 )
rglwidget()
try(rgl.close())
```
?knit

